//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Logic/Core/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace CustomInputSystem
{
    public partial class @Controls : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @Controls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Global"",
            ""id"": ""ea508cac-7081-43e3-8b6a-96395a313066"",
            ""actions"": [
                {
                    ""name"": ""ClickInteraction"",
                    ""type"": ""Button"",
                    ""id"": ""3b3a568a-6b59-482c-a929-d8195a9bd689"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraMovement"",
                    ""type"": ""Button"",
                    ""id"": ""21612ca0-5b43-4049-8afe-aaa8aeab82a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""fd179ee1-f408-4171-b203-92fb7c4105d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aee544f0-a59e-43dd-b301-5c46ddebc79b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ClickInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0de9bec4-12b3-4db6-b8b5-47f846be58a9"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad9b2710-d272-4396-b5a5-fd70144af0c4"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MazeModification"",
            ""id"": ""c23f94ba-1c90-44b6-bf5e-4fb2650735ae"",
            ""actions"": [
                {
                    ""name"": ""SetDefaultNode"",
                    ""type"": ""Button"",
                    ""id"": ""52638b61-d100-4dec-93b9-4e6dda2ee41e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetStartNode"",
                    ""type"": ""Button"",
                    ""id"": ""9c93bb33-3c91-443c-8775-175cac470b99"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetDestinationNode"",
                    ""type"": ""Button"",
                    ""id"": ""b02d61aa-438b-456e-8b8d-d280bca0cc9a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetBlockedNode"",
                    ""type"": ""Button"",
                    ""id"": ""d6ed8379-0573-4b4e-8eac-bc1ef9967af1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e681bda9-1fe1-4c9d-a8ea-63e710380c6a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SetDefaultNode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea261d96-21eb-4beb-a5b3-e0da1f96efb8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SetStartNode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de104dd1-3299-433e-b15f-f11bac5c55f7"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SetDestinationNode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e2dacf1-5f80-4d50-898e-09c5a48906f9"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SetBlockedNode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Algorithm"",
            ""id"": ""aea854b9-c22e-467f-9790-b71b45ccaac3"",
            ""actions"": [
                {
                    ""name"": ""Play"",
                    ""type"": ""Button"",
                    ""id"": ""49551d10-18d7-4b67-be85-f4d8530cff89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""93fe8ad3-fc46-45e3-b601-9e96933bb6cf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Step"",
                    ""type"": ""Button"",
                    ""id"": ""3db0c2c5-76cb-45ee-8e24-aa0937449e51"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stop"",
                    ""type"": ""Button"",
                    ""id"": ""bd298785-1973-4679-a849-627e089a8960"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8a6a38f4-c4ad-421d-98d9-e06c0ce37c44"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Play"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e697d12-2dd8-41e8-bd37-0b4a9ddab1ed"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71af2d27-509f-4490-aa70-216d1055164e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Step"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1dcdc9f5-666b-400a-bc6c-3d54d95785d3"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""026e4061-f9d8-4d20-be0c-150e7cae8153"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""217d086b-623d-4516-8266-787da3e2b1b1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""2b097356-873c-4d6d-a1d8-fa98a0d0850e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""02f4a0b9-8dcd-41b8-9ddb-f37af1179f84"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""59dc9414-6f6a-473f-8e2b-242f5313a498"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""df98d7a6-aeb7-4140-9163-d940dbe440fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""623891ec-23b0-4a9a-8311-e4e56127a77b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c44e4c24-d111-4567-b601-5c2130cc9ae1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""85ae5e5a-693d-421a-9171-2d125abc8812"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""44adbefd-d393-4df9-bbbc-a10e08a8d918"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""75a0f23f-2604-413d-869c-290e0e4ed154"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""97ce3ab4-d653-4920-a51c-29c2016f00ae"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4b6394db-9a11-4402-8672-e5ada7bcdaae"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e9e78da7-d906-4c91-8df1-ee7d98e5e9c3"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""81da3cf3-8349-4aeb-bda0-06e75b6c3f41"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c067a234-efed-405f-9d97-38e6b0a02a0a"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""927d84b3-0c06-471c-a7f1-ddda3cbdc8b3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2736635-48d7-4201-9294-522e9fe846f6"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""873ab924-43a7-4f9c-bbeb-a3a6d86d0800"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""61c8ae5b-a744-426b-a07b-169a2896e713"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3a0dd4a0-a0ed-4ab9-89f6-7c8973030733"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Popup"",
            ""id"": ""59d57059-7028-424f-a848-9ade27b8d5ad"",
            ""actions"": [
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""d962d7ef-778c-4ce7-a698-95a4b24ea9f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Close"",
                    ""type"": ""Button"",
                    ""id"": ""e7778be0-28d0-4a78-8a24-eeab60263fc8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d856519b-89f6-4cda-b71d-83c6ea909170"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef0327af-134b-4239-8e44-30990c48b5fc"",
                    ""path"": ""<Keyboard>/numpadEnter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""340af6d1-0c5b-4733-a220-1d5042088a3a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Close"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Global
            m_Global = asset.FindActionMap("Global", throwIfNotFound: true);
            m_Global_ClickInteraction = m_Global.FindAction("ClickInteraction", throwIfNotFound: true);
            m_Global_CameraMovement = m_Global.FindAction("CameraMovement", throwIfNotFound: true);
            m_Global_Back = m_Global.FindAction("Back", throwIfNotFound: true);
            // MazeModification
            m_MazeModification = asset.FindActionMap("MazeModification", throwIfNotFound: true);
            m_MazeModification_SetDefaultNode = m_MazeModification.FindAction("SetDefaultNode", throwIfNotFound: true);
            m_MazeModification_SetStartNode = m_MazeModification.FindAction("SetStartNode", throwIfNotFound: true);
            m_MazeModification_SetDestinationNode = m_MazeModification.FindAction("SetDestinationNode", throwIfNotFound: true);
            m_MazeModification_SetBlockedNode = m_MazeModification.FindAction("SetBlockedNode", throwIfNotFound: true);
            // Algorithm
            m_Algorithm = asset.FindActionMap("Algorithm", throwIfNotFound: true);
            m_Algorithm_Play = m_Algorithm.FindAction("Play", throwIfNotFound: true);
            m_Algorithm_Pause = m_Algorithm.FindAction("Pause", throwIfNotFound: true);
            m_Algorithm_Step = m_Algorithm.FindAction("Step", throwIfNotFound: true);
            m_Algorithm_Stop = m_Algorithm.FindAction("Stop", throwIfNotFound: true);
            // UI
            m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
            m_UI_Navigate = m_UI.FindAction("Navigate", throwIfNotFound: true);
            m_UI_Submit = m_UI.FindAction("Submit", throwIfNotFound: true);
            m_UI_Cancel = m_UI.FindAction("Cancel", throwIfNotFound: true);
            m_UI_Point = m_UI.FindAction("Point", throwIfNotFound: true);
            m_UI_Click = m_UI.FindAction("Click", throwIfNotFound: true);
            m_UI_ScrollWheel = m_UI.FindAction("ScrollWheel", throwIfNotFound: true);
            m_UI_MiddleClick = m_UI.FindAction("MiddleClick", throwIfNotFound: true);
            m_UI_RightClick = m_UI.FindAction("RightClick", throwIfNotFound: true);
            // Popup
            m_Popup = asset.FindActionMap("Popup", throwIfNotFound: true);
            m_Popup_Confirm = m_Popup.FindAction("Confirm", throwIfNotFound: true);
            m_Popup_Close = m_Popup.FindAction("Close", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Global
        private readonly InputActionMap m_Global;
        private IGlobalActions m_GlobalActionsCallbackInterface;
        private readonly InputAction m_Global_ClickInteraction;
        private readonly InputAction m_Global_CameraMovement;
        private readonly InputAction m_Global_Back;
        public struct GlobalActions
        {
            private @Controls m_Wrapper;
            public GlobalActions(@Controls wrapper) { m_Wrapper = wrapper; }
            public InputAction @ClickInteraction => m_Wrapper.m_Global_ClickInteraction;
            public InputAction @CameraMovement => m_Wrapper.m_Global_CameraMovement;
            public InputAction @Back => m_Wrapper.m_Global_Back;
            public InputActionMap Get() { return m_Wrapper.m_Global; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GlobalActions set) { return set.Get(); }
            public void SetCallbacks(IGlobalActions instance)
            {
                if (m_Wrapper.m_GlobalActionsCallbackInterface != null)
                {
                    @ClickInteraction.started -= m_Wrapper.m_GlobalActionsCallbackInterface.OnClickInteraction;
                    @ClickInteraction.performed -= m_Wrapper.m_GlobalActionsCallbackInterface.OnClickInteraction;
                    @ClickInteraction.canceled -= m_Wrapper.m_GlobalActionsCallbackInterface.OnClickInteraction;
                    @CameraMovement.started -= m_Wrapper.m_GlobalActionsCallbackInterface.OnCameraMovement;
                    @CameraMovement.performed -= m_Wrapper.m_GlobalActionsCallbackInterface.OnCameraMovement;
                    @CameraMovement.canceled -= m_Wrapper.m_GlobalActionsCallbackInterface.OnCameraMovement;
                    @Back.started -= m_Wrapper.m_GlobalActionsCallbackInterface.OnBack;
                    @Back.performed -= m_Wrapper.m_GlobalActionsCallbackInterface.OnBack;
                    @Back.canceled -= m_Wrapper.m_GlobalActionsCallbackInterface.OnBack;
                }
                m_Wrapper.m_GlobalActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @ClickInteraction.started += instance.OnClickInteraction;
                    @ClickInteraction.performed += instance.OnClickInteraction;
                    @ClickInteraction.canceled += instance.OnClickInteraction;
                    @CameraMovement.started += instance.OnCameraMovement;
                    @CameraMovement.performed += instance.OnCameraMovement;
                    @CameraMovement.canceled += instance.OnCameraMovement;
                    @Back.started += instance.OnBack;
                    @Back.performed += instance.OnBack;
                    @Back.canceled += instance.OnBack;
                }
            }
        }
        public GlobalActions @Global => new GlobalActions(this);

        // MazeModification
        private readonly InputActionMap m_MazeModification;
        private IMazeModificationActions m_MazeModificationActionsCallbackInterface;
        private readonly InputAction m_MazeModification_SetDefaultNode;
        private readonly InputAction m_MazeModification_SetStartNode;
        private readonly InputAction m_MazeModification_SetDestinationNode;
        private readonly InputAction m_MazeModification_SetBlockedNode;
        public struct MazeModificationActions
        {
            private @Controls m_Wrapper;
            public MazeModificationActions(@Controls wrapper) { m_Wrapper = wrapper; }
            public InputAction @SetDefaultNode => m_Wrapper.m_MazeModification_SetDefaultNode;
            public InputAction @SetStartNode => m_Wrapper.m_MazeModification_SetStartNode;
            public InputAction @SetDestinationNode => m_Wrapper.m_MazeModification_SetDestinationNode;
            public InputAction @SetBlockedNode => m_Wrapper.m_MazeModification_SetBlockedNode;
            public InputActionMap Get() { return m_Wrapper.m_MazeModification; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MazeModificationActions set) { return set.Get(); }
            public void SetCallbacks(IMazeModificationActions instance)
            {
                if (m_Wrapper.m_MazeModificationActionsCallbackInterface != null)
                {
                    @SetDefaultNode.started -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetDefaultNode;
                    @SetDefaultNode.performed -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetDefaultNode;
                    @SetDefaultNode.canceled -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetDefaultNode;
                    @SetStartNode.started -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetStartNode;
                    @SetStartNode.performed -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetStartNode;
                    @SetStartNode.canceled -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetStartNode;
                    @SetDestinationNode.started -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetDestinationNode;
                    @SetDestinationNode.performed -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetDestinationNode;
                    @SetDestinationNode.canceled -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetDestinationNode;
                    @SetBlockedNode.started -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetBlockedNode;
                    @SetBlockedNode.performed -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetBlockedNode;
                    @SetBlockedNode.canceled -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetBlockedNode;
                }
                m_Wrapper.m_MazeModificationActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @SetDefaultNode.started += instance.OnSetDefaultNode;
                    @SetDefaultNode.performed += instance.OnSetDefaultNode;
                    @SetDefaultNode.canceled += instance.OnSetDefaultNode;
                    @SetStartNode.started += instance.OnSetStartNode;
                    @SetStartNode.performed += instance.OnSetStartNode;
                    @SetStartNode.canceled += instance.OnSetStartNode;
                    @SetDestinationNode.started += instance.OnSetDestinationNode;
                    @SetDestinationNode.performed += instance.OnSetDestinationNode;
                    @SetDestinationNode.canceled += instance.OnSetDestinationNode;
                    @SetBlockedNode.started += instance.OnSetBlockedNode;
                    @SetBlockedNode.performed += instance.OnSetBlockedNode;
                    @SetBlockedNode.canceled += instance.OnSetBlockedNode;
                }
            }
        }
        public MazeModificationActions @MazeModification => new MazeModificationActions(this);

        // Algorithm
        private readonly InputActionMap m_Algorithm;
        private IAlgorithmActions m_AlgorithmActionsCallbackInterface;
        private readonly InputAction m_Algorithm_Play;
        private readonly InputAction m_Algorithm_Pause;
        private readonly InputAction m_Algorithm_Step;
        private readonly InputAction m_Algorithm_Stop;
        public struct AlgorithmActions
        {
            private @Controls m_Wrapper;
            public AlgorithmActions(@Controls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Play => m_Wrapper.m_Algorithm_Play;
            public InputAction @Pause => m_Wrapper.m_Algorithm_Pause;
            public InputAction @Step => m_Wrapper.m_Algorithm_Step;
            public InputAction @Stop => m_Wrapper.m_Algorithm_Stop;
            public InputActionMap Get() { return m_Wrapper.m_Algorithm; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(AlgorithmActions set) { return set.Get(); }
            public void SetCallbacks(IAlgorithmActions instance)
            {
                if (m_Wrapper.m_AlgorithmActionsCallbackInterface != null)
                {
                    @Play.started -= m_Wrapper.m_AlgorithmActionsCallbackInterface.OnPlay;
                    @Play.performed -= m_Wrapper.m_AlgorithmActionsCallbackInterface.OnPlay;
                    @Play.canceled -= m_Wrapper.m_AlgorithmActionsCallbackInterface.OnPlay;
                    @Pause.started -= m_Wrapper.m_AlgorithmActionsCallbackInterface.OnPause;
                    @Pause.performed -= m_Wrapper.m_AlgorithmActionsCallbackInterface.OnPause;
                    @Pause.canceled -= m_Wrapper.m_AlgorithmActionsCallbackInterface.OnPause;
                    @Step.started -= m_Wrapper.m_AlgorithmActionsCallbackInterface.OnStep;
                    @Step.performed -= m_Wrapper.m_AlgorithmActionsCallbackInterface.OnStep;
                    @Step.canceled -= m_Wrapper.m_AlgorithmActionsCallbackInterface.OnStep;
                    @Stop.started -= m_Wrapper.m_AlgorithmActionsCallbackInterface.OnStop;
                    @Stop.performed -= m_Wrapper.m_AlgorithmActionsCallbackInterface.OnStop;
                    @Stop.canceled -= m_Wrapper.m_AlgorithmActionsCallbackInterface.OnStop;
                }
                m_Wrapper.m_AlgorithmActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Play.started += instance.OnPlay;
                    @Play.performed += instance.OnPlay;
                    @Play.canceled += instance.OnPlay;
                    @Pause.started += instance.OnPause;
                    @Pause.performed += instance.OnPause;
                    @Pause.canceled += instance.OnPause;
                    @Step.started += instance.OnStep;
                    @Step.performed += instance.OnStep;
                    @Step.canceled += instance.OnStep;
                    @Stop.started += instance.OnStop;
                    @Stop.performed += instance.OnStop;
                    @Stop.canceled += instance.OnStop;
                }
            }
        }
        public AlgorithmActions @Algorithm => new AlgorithmActions(this);

        // UI
        private readonly InputActionMap m_UI;
        private IUIActions m_UIActionsCallbackInterface;
        private readonly InputAction m_UI_Navigate;
        private readonly InputAction m_UI_Submit;
        private readonly InputAction m_UI_Cancel;
        private readonly InputAction m_UI_Point;
        private readonly InputAction m_UI_Click;
        private readonly InputAction m_UI_ScrollWheel;
        private readonly InputAction m_UI_MiddleClick;
        private readonly InputAction m_UI_RightClick;
        public struct UIActions
        {
            private @Controls m_Wrapper;
            public UIActions(@Controls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Navigate => m_Wrapper.m_UI_Navigate;
            public InputAction @Submit => m_Wrapper.m_UI_Submit;
            public InputAction @Cancel => m_Wrapper.m_UI_Cancel;
            public InputAction @Point => m_Wrapper.m_UI_Point;
            public InputAction @Click => m_Wrapper.m_UI_Click;
            public InputAction @ScrollWheel => m_Wrapper.m_UI_ScrollWheel;
            public InputAction @MiddleClick => m_Wrapper.m_UI_MiddleClick;
            public InputAction @RightClick => m_Wrapper.m_UI_RightClick;
            public InputActionMap Get() { return m_Wrapper.m_UI; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
            public void SetCallbacks(IUIActions instance)
            {
                if (m_Wrapper.m_UIActionsCallbackInterface != null)
                {
                    @Navigate.started -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                    @Navigate.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                    @Navigate.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                    @Submit.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                    @Submit.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                    @Submit.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                    @Cancel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                    @Cancel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                    @Cancel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                    @Point.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                    @Point.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                    @Point.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                    @Click.started -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                    @Click.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                    @Click.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                    @ScrollWheel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                    @ScrollWheel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                    @ScrollWheel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                    @MiddleClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                    @MiddleClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                    @MiddleClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                    @RightClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                    @RightClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                    @RightClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                }
                m_Wrapper.m_UIActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Navigate.started += instance.OnNavigate;
                    @Navigate.performed += instance.OnNavigate;
                    @Navigate.canceled += instance.OnNavigate;
                    @Submit.started += instance.OnSubmit;
                    @Submit.performed += instance.OnSubmit;
                    @Submit.canceled += instance.OnSubmit;
                    @Cancel.started += instance.OnCancel;
                    @Cancel.performed += instance.OnCancel;
                    @Cancel.canceled += instance.OnCancel;
                    @Point.started += instance.OnPoint;
                    @Point.performed += instance.OnPoint;
                    @Point.canceled += instance.OnPoint;
                    @Click.started += instance.OnClick;
                    @Click.performed += instance.OnClick;
                    @Click.canceled += instance.OnClick;
                    @ScrollWheel.started += instance.OnScrollWheel;
                    @ScrollWheel.performed += instance.OnScrollWheel;
                    @ScrollWheel.canceled += instance.OnScrollWheel;
                    @MiddleClick.started += instance.OnMiddleClick;
                    @MiddleClick.performed += instance.OnMiddleClick;
                    @MiddleClick.canceled += instance.OnMiddleClick;
                    @RightClick.started += instance.OnRightClick;
                    @RightClick.performed += instance.OnRightClick;
                    @RightClick.canceled += instance.OnRightClick;
                }
            }
        }
        public UIActions @UI => new UIActions(this);

        // Popup
        private readonly InputActionMap m_Popup;
        private IPopupActions m_PopupActionsCallbackInterface;
        private readonly InputAction m_Popup_Confirm;
        private readonly InputAction m_Popup_Close;
        public struct PopupActions
        {
            private @Controls m_Wrapper;
            public PopupActions(@Controls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Confirm => m_Wrapper.m_Popup_Confirm;
            public InputAction @Close => m_Wrapper.m_Popup_Close;
            public InputActionMap Get() { return m_Wrapper.m_Popup; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PopupActions set) { return set.Get(); }
            public void SetCallbacks(IPopupActions instance)
            {
                if (m_Wrapper.m_PopupActionsCallbackInterface != null)
                {
                    @Confirm.started -= m_Wrapper.m_PopupActionsCallbackInterface.OnConfirm;
                    @Confirm.performed -= m_Wrapper.m_PopupActionsCallbackInterface.OnConfirm;
                    @Confirm.canceled -= m_Wrapper.m_PopupActionsCallbackInterface.OnConfirm;
                    @Close.started -= m_Wrapper.m_PopupActionsCallbackInterface.OnClose;
                    @Close.performed -= m_Wrapper.m_PopupActionsCallbackInterface.OnClose;
                    @Close.canceled -= m_Wrapper.m_PopupActionsCallbackInterface.OnClose;
                }
                m_Wrapper.m_PopupActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @Confirm.started += instance.OnConfirm;
                    @Confirm.performed += instance.OnConfirm;
                    @Confirm.canceled += instance.OnConfirm;
                    @Close.started += instance.OnClose;
                    @Close.performed += instance.OnClose;
                    @Close.canceled += instance.OnClose;
                }
            }
        }
        public PopupActions @Popup => new PopupActions(this);
        private int m_KeyboardMouseSchemeIndex = -1;
        public InputControlScheme KeyboardMouseScheme
        {
            get
            {
                if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
                return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
            }
        }
        public interface IGlobalActions
        {
            void OnClickInteraction(InputAction.CallbackContext context);
            void OnCameraMovement(InputAction.CallbackContext context);
            void OnBack(InputAction.CallbackContext context);
        }
        public interface IMazeModificationActions
        {
            void OnSetDefaultNode(InputAction.CallbackContext context);
            void OnSetStartNode(InputAction.CallbackContext context);
            void OnSetDestinationNode(InputAction.CallbackContext context);
            void OnSetBlockedNode(InputAction.CallbackContext context);
        }
        public interface IAlgorithmActions
        {
            void OnPlay(InputAction.CallbackContext context);
            void OnPause(InputAction.CallbackContext context);
            void OnStep(InputAction.CallbackContext context);
            void OnStop(InputAction.CallbackContext context);
        }
        public interface IUIActions
        {
            void OnNavigate(InputAction.CallbackContext context);
            void OnSubmit(InputAction.CallbackContext context);
            void OnCancel(InputAction.CallbackContext context);
            void OnPoint(InputAction.CallbackContext context);
            void OnClick(InputAction.CallbackContext context);
            void OnScrollWheel(InputAction.CallbackContext context);
            void OnMiddleClick(InputAction.CallbackContext context);
            void OnRightClick(InputAction.CallbackContext context);
        }
        public interface IPopupActions
        {
            void OnConfirm(InputAction.CallbackContext context);
            void OnClose(InputAction.CallbackContext context);
        }
    }
}
