//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Game/Core/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace CustomInputSystem
{
    public partial class @Controls : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @Controls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Global"",
            ""id"": ""ea508cac-7081-43e3-8b6a-96395a313066"",
            ""actions"": [
                {
                    ""name"": ""ClickInteraction"",
                    ""type"": ""Button"",
                    ""id"": ""3b3a568a-6b59-482c-a929-d8195a9bd689"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraMovement"",
                    ""type"": ""Button"",
                    ""id"": ""21612ca0-5b43-4049-8afe-aaa8aeab82a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aee544f0-a59e-43dd-b301-5c46ddebc79b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ClickInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0de9bec4-12b3-4db6-b8b5-47f846be58a9"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""CameraMovement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MazeModification"",
            ""id"": ""c23f94ba-1c90-44b6-bf5e-4fb2650735ae"",
            ""actions"": [
                {
                    ""name"": ""SetDefaultNode"",
                    ""type"": ""Button"",
                    ""id"": ""52638b61-d100-4dec-93b9-4e6dda2ee41e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetStartNode"",
                    ""type"": ""Button"",
                    ""id"": ""9c93bb33-3c91-443c-8775-175cac470b99"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetDestinationNode"",
                    ""type"": ""Button"",
                    ""id"": ""b02d61aa-438b-456e-8b8d-d280bca0cc9a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SetBlockedNode"",
                    ""type"": ""Button"",
                    ""id"": ""d6ed8379-0573-4b4e-8eac-bc1ef9967af1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e681bda9-1fe1-4c9d-a8ea-63e710380c6a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SetDefaultNode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea261d96-21eb-4beb-a5b3-e0da1f96efb8"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SetStartNode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de104dd1-3299-433e-b15f-f11bac5c55f7"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SetDestinationNode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e2dacf1-5f80-4d50-898e-09c5a48906f9"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SetBlockedNode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // Global
            m_Global = asset.FindActionMap("Global", throwIfNotFound: true);
            m_Global_ClickInteraction = m_Global.FindAction("ClickInteraction", throwIfNotFound: true);
            m_Global_CameraMovement = m_Global.FindAction("CameraMovement", throwIfNotFound: true);
            // MazeModification
            m_MazeModification = asset.FindActionMap("MazeModification", throwIfNotFound: true);
            m_MazeModification_SetDefaultNode = m_MazeModification.FindAction("SetDefaultNode", throwIfNotFound: true);
            m_MazeModification_SetStartNode = m_MazeModification.FindAction("SetStartNode", throwIfNotFound: true);
            m_MazeModification_SetDestinationNode = m_MazeModification.FindAction("SetDestinationNode", throwIfNotFound: true);
            m_MazeModification_SetBlockedNode = m_MazeModification.FindAction("SetBlockedNode", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Global
        private readonly InputActionMap m_Global;
        private IGlobalActions m_GlobalActionsCallbackInterface;
        private readonly InputAction m_Global_ClickInteraction;
        private readonly InputAction m_Global_CameraMovement;
        public struct GlobalActions
        {
            private @Controls m_Wrapper;
            public GlobalActions(@Controls wrapper) { m_Wrapper = wrapper; }
            public InputAction @ClickInteraction => m_Wrapper.m_Global_ClickInteraction;
            public InputAction @CameraMovement => m_Wrapper.m_Global_CameraMovement;
            public InputActionMap Get() { return m_Wrapper.m_Global; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GlobalActions set) { return set.Get(); }
            public void SetCallbacks(IGlobalActions instance)
            {
                if (m_Wrapper.m_GlobalActionsCallbackInterface != null)
                {
                    @ClickInteraction.started -= m_Wrapper.m_GlobalActionsCallbackInterface.OnClickInteraction;
                    @ClickInteraction.performed -= m_Wrapper.m_GlobalActionsCallbackInterface.OnClickInteraction;
                    @ClickInteraction.canceled -= m_Wrapper.m_GlobalActionsCallbackInterface.OnClickInteraction;
                    @CameraMovement.started -= m_Wrapper.m_GlobalActionsCallbackInterface.OnCameraMovement;
                    @CameraMovement.performed -= m_Wrapper.m_GlobalActionsCallbackInterface.OnCameraMovement;
                    @CameraMovement.canceled -= m_Wrapper.m_GlobalActionsCallbackInterface.OnCameraMovement;
                }
                m_Wrapper.m_GlobalActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @ClickInteraction.started += instance.OnClickInteraction;
                    @ClickInteraction.performed += instance.OnClickInteraction;
                    @ClickInteraction.canceled += instance.OnClickInteraction;
                    @CameraMovement.started += instance.OnCameraMovement;
                    @CameraMovement.performed += instance.OnCameraMovement;
                    @CameraMovement.canceled += instance.OnCameraMovement;
                }
            }
        }
        public GlobalActions @Global => new GlobalActions(this);

        // MazeModification
        private readonly InputActionMap m_MazeModification;
        private IMazeModificationActions m_MazeModificationActionsCallbackInterface;
        private readonly InputAction m_MazeModification_SetDefaultNode;
        private readonly InputAction m_MazeModification_SetStartNode;
        private readonly InputAction m_MazeModification_SetDestinationNode;
        private readonly InputAction m_MazeModification_SetBlockedNode;
        public struct MazeModificationActions
        {
            private @Controls m_Wrapper;
            public MazeModificationActions(@Controls wrapper) { m_Wrapper = wrapper; }
            public InputAction @SetDefaultNode => m_Wrapper.m_MazeModification_SetDefaultNode;
            public InputAction @SetStartNode => m_Wrapper.m_MazeModification_SetStartNode;
            public InputAction @SetDestinationNode => m_Wrapper.m_MazeModification_SetDestinationNode;
            public InputAction @SetBlockedNode => m_Wrapper.m_MazeModification_SetBlockedNode;
            public InputActionMap Get() { return m_Wrapper.m_MazeModification; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(MazeModificationActions set) { return set.Get(); }
            public void SetCallbacks(IMazeModificationActions instance)
            {
                if (m_Wrapper.m_MazeModificationActionsCallbackInterface != null)
                {
                    @SetDefaultNode.started -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetDefaultNode;
                    @SetDefaultNode.performed -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetDefaultNode;
                    @SetDefaultNode.canceled -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetDefaultNode;
                    @SetStartNode.started -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetStartNode;
                    @SetStartNode.performed -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetStartNode;
                    @SetStartNode.canceled -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetStartNode;
                    @SetDestinationNode.started -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetDestinationNode;
                    @SetDestinationNode.performed -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetDestinationNode;
                    @SetDestinationNode.canceled -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetDestinationNode;
                    @SetBlockedNode.started -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetBlockedNode;
                    @SetBlockedNode.performed -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetBlockedNode;
                    @SetBlockedNode.canceled -= m_Wrapper.m_MazeModificationActionsCallbackInterface.OnSetBlockedNode;
                }
                m_Wrapper.m_MazeModificationActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @SetDefaultNode.started += instance.OnSetDefaultNode;
                    @SetDefaultNode.performed += instance.OnSetDefaultNode;
                    @SetDefaultNode.canceled += instance.OnSetDefaultNode;
                    @SetStartNode.started += instance.OnSetStartNode;
                    @SetStartNode.performed += instance.OnSetStartNode;
                    @SetStartNode.canceled += instance.OnSetStartNode;
                    @SetDestinationNode.started += instance.OnSetDestinationNode;
                    @SetDestinationNode.performed += instance.OnSetDestinationNode;
                    @SetDestinationNode.canceled += instance.OnSetDestinationNode;
                    @SetBlockedNode.started += instance.OnSetBlockedNode;
                    @SetBlockedNode.performed += instance.OnSetBlockedNode;
                    @SetBlockedNode.canceled += instance.OnSetBlockedNode;
                }
            }
        }
        public MazeModificationActions @MazeModification => new MazeModificationActions(this);
        private int m_KeyboardMouseSchemeIndex = -1;
        public InputControlScheme KeyboardMouseScheme
        {
            get
            {
                if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
                return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
            }
        }
        public interface IGlobalActions
        {
            void OnClickInteraction(InputAction.CallbackContext context);
            void OnCameraMovement(InputAction.CallbackContext context);
        }
        public interface IMazeModificationActions
        {
            void OnSetDefaultNode(InputAction.CallbackContext context);
            void OnSetStartNode(InputAction.CallbackContext context);
            void OnSetDestinationNode(InputAction.CallbackContext context);
            void OnSetBlockedNode(InputAction.CallbackContext context);
        }
    }
}
